### ISSUE TITLE
(version 3.12.5) Crash

### ISSUE THREAD

**Issue by ethantallent** [ZolanaPrime/stellaris-small-tweaks#4]
Hello,
When attempting to run the mod script via powershell, instead of opening up the command prompt to input preferences as indicated in the manual, the command prompt flashes a few red lines of text and then closes before I am able to read them. I assume there is some issue with the recent update that is preventing the script from running as intended. I hope this is helpful.

**Comment by ZolanaPrime** [comment]
Hi, thanks for that.  Unfortunately I am unable to reproduce the issue on my end. 

In order to get the contents of the red text, can you open and try and run the script using the PowerShell ISE that should be part of your Windows installation. (Typically found Start->Programs->Administrative Tools->Windows PowerShell ISE).  Open the script in there and press the green Play button to run it.  If you can get the text, and update the issue here, that'd be ideal - thanks!

**Comment by ZolanaPrime** [comment]
Cannot reproduce error, no updates provided.

**Comment by Kevalya223** [comment]
Hey man I found a fix for this. You need to download the ps1 file and then copy its content and paste it in the latest version of powershell. On the first prompt select your Stellaris folder and on the second prompt select the folder where you downloaded the ps1 file.

**Comment by ZolanaPrime** [comment]
That makes sense if it's a permissions issue - PowerShell will be treating it as if you wrote the script yourself as opposed to downloading it from the internet. Glad it solved it though!
